In [7]:
import pandas as pd

In [8]:
df=pd.read_csv(r"C:\Users\Mikey\Documents\spotify_millsongdata.csv")

In [9]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [10]:
df.shape

(57650, 4)

In [11]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [12]:
df= df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [13]:
df['text'][0]

"Sittin' in the mornin' sun  \r\nI'll be sittin' when the evening comes  \r\nWatchin' the ships roll in  \r\nThen I watch 'em roll away again, yeah  \r\n  \r\nI'm sittin' on the dock of the bay  \r\nWatchin' the tide roll away  \r\nJust sittin on the dock of the bay  \r\nWastin' time  \r\n  \r\nI left my home in Georgia  \r\nHeaded for the Frisco Bay  \r\nI have nothing to live for  \r\nLook like nothing's gonna come my way, yeah  \r\n  \r\nSo I'm sittin' on the dock of the bay  \r\nWatchin' the tide roll away  \r\nYes, I'm just sittin' on the dock of the bay  \r\nWastin' time  \r\n  \r\nLook like nothing's gonna change  \r\nEverything still remains the same  \r\nI can't do what ten people tell me to do  \r\nSo, I guess I'll remain the same  \r\n  \r\nSittin' hear resting my bones  \r\nAnd this loneliness won't leave me alone, yeah  \r\nBut two thousand miles I roam  \r\nJust to make this dock my home, yeah  \r\n  \r\nNow I'm sittin' at the dock of the bay  \r\nWatching the tide roll away, yeah  \r\nI'm just sittin' on the dock of the bay  \r\nWasting time\r\n\r\n"

In [14]:
df.shape

(5000, 3)

In [15]:
#Text cleaning
df['text']= df['text'].str.lower().replace(r'^\w\s','').replace(r'\n', ' ', regex= True)

In [16]:
df.tail(5)

,artist,song,text
4995,Lucky Dube,Teach The World,it takes a million people \r to build up a go...
4996,Chris Rea,Nothing To Fear,i feel your heat in dusty whispers \r the win...
4997,Yellowcard,Shadows And Regrets,"i'm back, back in town \r and everything has ..."
4998,Alice Cooper,Mr And Misdemeanor,mr and misdemeanor \r middle of the roaders ...
4999,Kiss,Do You Remember Rock'n'Roll Radio,"do you remember hullabaloo, \r upbeat, shindi..."

In [18]:
pip install -U nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click in c:\users\mikey\appdata\roaming\python\python313\site-packages (from nltk) (8.1.8)
Collecting joblib (from nltk)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\mikey\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 912.4 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.5 MB 925.6 kB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 984.3 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 1.0 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl (273 kB)
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, joblib, nltk
Successfully installed joblib-1.4.2 nltk-3.9.1 regex-2024.11.6 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize

In [20]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mikey\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [21]:
import nltk
print(nltk.data.path)

['C:\\Users\\Mikey/nltk_data', 'c:\\Python313\\nltk_data', 'c:\\Python313\\share\\nltk_data', 'c:\\Python313\\lib\\nltk_data', 'C:\\Users\\Mikey\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']

In [22]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mikey\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [23]:
stemmer = PorterStemmer()

In [24]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a= [stemmer.stem(w) for w in token]
    return " ".join(a)

In [28]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\mikey\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.2.5)
Requirement already satisfied: scipy>=1.6.0 in c:\users\mikey\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mikey\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.4.2)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.1 MB 1.8 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/11.1 MB 1.8 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/11.1 MB 1.8 MB/s eta 0:00:06
   ------- -------------------------------- 2.1/11.1 MB 2.0 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.1 MB 2.1 MB/s eta 0:00:05
   ------------ --------------------------- 3.4/11.1 MB 2.3 MB/s eta 0:00:04
   --------------- ------------------------ 4.2/11.1 MB 2.4 MB/s eta 0:00:03
   ----------------- ---------------------- 4.7/11.1 MB 2.4 MB/s eta 0:00:03
   ------------------- -------------------- 5.5/11.1 MB 2.6 MB/s eta 0:00:03
   ---------------------- ----------------- 6.3/11.1 MB 2.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.1 MB 2.8 MB/s eta 0:00:02
   ---------------------------- ----------- 7.9/11.1 MB 2.8 MB/s eta 0:00:02
   -------------------------------- ------- 8.9/11.1 MB 3.0 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/11.1 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.1 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 2.8 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scikit-learn
Successfully installed scikit-learn-1.6.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
tfid= TfidfVectorizer(analyzer='word', stop_words='english')

In [31]:
matrix=tfid.fit_transform(df['text'])

In [32]:
similer=cosine_similarity(matrix)

In [33]:
similer[0]

array([1.        , 0.00356284, 0.00112446, ..., 0.00371256, 0.04225107,
       0.03824674], shape=(5000,))

In [34]:
df[df['song']=='Speak Of The Devil'].index[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

**Recommender function**

In [35]:
def recommender(song_name):
    idx = df[df['song']=='Waiting For The Man'].index[0]
    distance = sorted(list(enumerate(similer[idx])), reverse=True, key= lambda x:x[1])
    song= []
    for s_id in distance[1:5]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [36]:
df.head(10)

,artist,song,text
0,Glen Campbell,Sittin' On The Dock Of The Bay,sittin' in the mornin' sun \r i'll be sittin'...
1,Dean Martin,I've Grown Accustomed To Her Face,i've grown accustomed to her face \r she almo...
2,Weezer,Christmas Song,you told me you would be here by my side \r w...
3,Warren Zevon,Carmelita,i hear mariachi static on my radio \r and the...
4,Kim Wilde,Action City,suddenly there's a shadow on a nation \r sudd...
5,Kinks,Demolition,i spy with my little eye \r anything here tha...
6,Olivia Newton-John,Don't Say That,"""i love you,"" ""i want you,"" ""i need you"" \r a..."
7,Great Big Sea,Love Me Tonight,we've waited all this time \r this long and l...
8,Bonnie Raitt,Longing In Their Hearts,let me tell you 'bout a friend of mine \r he'...
9,Frank Sinatra,All Through The Day,"i sit alone in the golden daylight, \r but al..."

In [37]:
import pickle

In [38]:
pickle.dump(similer,open("similarity", "wb"))

In [39]:
pickle.dump(df, open("df", "wb"))